### PR TITLE
Lpgd class

### PR DESCRIPTION
**Pull request by jabascal**
Added Learned PGD, remove old classes

### CODE REVIEW

**Comment by nducros** [comment]
For some reason the new classes (i.e., `DCDRUNet`, `LearnedPGD`, etc) do not show up in the [documentation](https://spyrit.readthedocs.io/en/lpgd_class/_autosummary/spyrit.core.recon.html#)

@jabascal does it work locally?
@romainphan the autosummary seems to [work well](https://readthedocs.org/projects/spyrit/builds/24598596/). Is there anything to do manually?

**Comment by romainphan** [comment]
@nducros 

I see no DCDRUNet class here https://github.com/openspyrit/spyrit/blob/lpgd_class/spyrit/core/recon.py

as for LearnedPGD, it actually does show up in the version you linked to. Maybe there was a build recently ?

**Comment by nducros** [comment]
I was checking a cached version. I now see LearnedPGD, thx ! 
DCDRUNet is in `external`. Does it make sense to add it to the autodoc, even if documentation will be minimal?

**Comment by romainphan** [comment]
I would never recommend not to document something... ^^

**Comment by romainphan** [comment]
If some bits of code are taken from elsewhere, could it be possible to link to that documentation ?
Also i can't see any dcdrunet class [here](https://github.com/openspyrit/spyrit/blob/lpgd_class/spyrit/external/drunet.py)

**Comment by nducros** [comment]
you're right! This is okay, though. My comment was confusing. The DCDRUnet method I mentionned is a `DCNet` used in conjunction with a `DRUNet`.

**Comment by romainphan** [comment]
I added this line
`spyrit.external`
to spyrit/docs/source/index.rst ([here](https://github.com/openspyrit/spyrit/blob/8f29dece1530fc018322529475c214f22451b062/docs/source/index.rst?plain=1#L128))

The documentation is compiled, you may have a look [here](https://spyrit.readthedocs.io/en/lpgd_class/_autosummary/spyrit.external.html) at what it looks like, but i believe all of it is empty

**Comment by nducros** [comment]
Quite empty but not so bad to have it.
@jabascal Can you update the docstring of DRUNet to indicate the input parameters, then I'll move on an merge.

**Comment by jabascal** [comment]
Updated LPGD and added description to DRUNet

**Comment by nducros** [comment]
A few typos are left (see [here](https://spyrit.readthedocs.io/en/lpgd_class/_autosummary/spyrit.external.drunet.DRUNet.html#spyrit.external.drunet.DRUNet)). 
Add also link to original repo?

**Comment by nducros** [comment]
@jabascal Does it look good ? [here](https://spyrit.readthedocs.io/en/lpgd_class/_autosummary/spyrit.external.drunet.DRUNet.html#spyrit.external.drunet.DRUNet)

B is the batch size, right? It was previously denoted BC, but I think it does not depend on the number of channels ? 
Should the number of channels of the input match the number of channel of DRUNet?

**Comment by jabascal** [comment]
Yes, DRUNet works on black and white and color images. It is tested only on
bw, I guess it should work. Yes, they should match

**Pull request merged**
