### PR TITLE
Hslsfm

### PR DESCRIPTION
**Pull request by nducros**

### CODE REVIEW

**Comment by nducros** [comment]
Update : 
* Documentation
* Shape of the output of Tikhonov (no reshape). I suggest to reshape in the calling methods (e.g., forward of Tikho1Net
* Add Tikho1Net

Can you check it works for you ?

**Comment by romainphan** [comment]
I adapted my code to the changed shape of the Tikhonov output.
Do you want me to review anything else ?

**Comment by nducros** [comment]
Great! Have you passed the tests? 
I just updated one file. Just check the doc / tuto. Then, you can merge.

**Comment by romainphan** [comment]
The tests are quite loose so they all passed.
I'm checking the documentation before tagging 2.4.

**Comment by romainphan** [comment]
is this branch ready to be merged to the master ?

**Comment by nducros** [comment]
(If the doc/tutorials look good) yes !

**Pull request merged**
