### PR TITLE
Tutos figs

### PR DESCRIPTION
**Pull request by jabascal**
Index docs

Updated Tutos 5 and 6, specially 5

### CODE REVIEW

**Comment by nducros** [comment]
I was not able to check you proposal

`Build #21956555
[tutos_figs](https://readthedocs.org/dashboard/spyrit/version/tutos_figs/edit/)
Build failed

Your builds will stop working soon!
"build.image" config key is deprecated and it will be removed soon. [Read our blog post to know how to migrate to new key "build.os"](https://blog.readthedocs.com/use-build-os-config/) and ensure your project continues building successfully.
Error

The configuration key "build.os" is required to build your documentation. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os`

@tbaudier: we can discuss it tomorrow?

**Comment by tbaudier** [comment]
It seems ok now:
https://spyrit.readthedocs.io/en/tutos_figs/gallery/index.html

**Comment by nducros** [comment]
@jabascal Tutos look good but thumbnails are not taken into account
https://spyrit.readthedocs.io/en/tutos_figs/gallery/index.html

**Comment by jabascal** [comment]
Selected thumbnails are not updated?

**Pull request merged**
