### PR TITLE
Add optic test and rename isbi test

### PR DESCRIPTION
**Pull request by tbaudier**
https://github.com/openspyrit/spyrit/issues/18

### CODE REVIEW

**Comment by tbaudier** [comment]
@nducros 
The data for the model do not contain `FileNotFoundError: [Errno 2] No such file or directory: 'data_example/model/NET_c0mp_N_64_M_512_epo_100_lr_0.001_sss_10_sdr_0.5_bs_256_reg_1e-07.pth`
needed by the Optic example. Do you prefer to add the correct model or to change the number of epoch, M, ... to match the existing data?

**Comment by nducros** [comment]
@tbaudier 
I checked `./model/` on [Tux](https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/) and it includes
`NET_c0mp_N0_2500_sig_0.5_N_64_M_1024_epo_20_lr_0.001_sss_10_sdr_0.5_bs_256_reg_1e-07.pth`. Do you have the same file in `data/example/` ?

@Antonio
Did you consider only 20 epochs?

**Comment by nducros** [comment]
You can try with `NET_c0mp_N_64_M_1024_epo_20_lr_0.001_sss_10_sdr_0.5_bs_256_reg_1e-07.pth`

**Comment by tbaudier** [comment]
@nducros Peux-tu vérifier le test optic sur ton PC stp ? Car là je ne m'en sors pas il manque toujours des données. Merci

**Comment by nducros** [comment]
@tbaudier The network filename issue is solved (I had to install `tabulate` and `bm3d` locally). I Got an other error. But let's see if we pass the CI ckecks anyway ;)

**Comment by nducros** [comment]
@tbaudier I also had to update and define several functions. There's an openBLAS issue now. This one is for you! (If necessary, we could also remove all lines related to BM3D which is not central here)

**Comment by nducros** [comment]
@tbaudier I removed to BM3D but I cannot go any further

**Comment by nducros** [comment]
@tbaudier Thanks Thomas! This is weird but there's still an error with pylops in test_wheel.

**Pull request merged**
