### PR TITLE
Merge iterative nets with  compNet

### PR DESCRIPTION
**Pull request by nducros**
Antonio's branch towards master

### CODE REVIEW

**Comment by nducros** [comment]
@tbaudier Can look at the checks that failed?
@atlorentemur (this was a comment from the pull request)

**Comment by tbaudier** [comment]
The error is:
```
...

100.0%
2021-07-22T10:47:47.4556961Z models
2021-07-22T10:47:47.4557299Z data
2021-07-22T10:47:47.4558255Z Downloading http://ai.stanford.edu/~acoates/stl10/stl10_binary.tar.gz to data/stl10_binary.tar.gz
2021-07-22T10:47:47.4559460Z Extracting data/stl10_binary.tar.gz to data
2021-07-22T10:47:47.4560069Z Files already downloaded and verified
2021-07-22T10:47:47.4560554Z Loading Cov and Mean
2021-07-22T10:47:47.4561465Z Measurement to image domain: statistical completion (no mean)
2021-07-22T10:47:47.4602072Z Traceback (most recent call last):
2021-07-22T10:47:47.4604041Z   File "../.github/workflows/example.py", line 90, in <module>
2021-07-22T10:47:47.4604754Z     load_net(title, model, device)
2021-07-22T10:47:47.4605448Z TypeError: load_net() takes 2 positional arguments but 3 were given
2021-07-22T10:47:48.0587755Z ##[error]Process completed with exit code 1.
```

The error comes from this line https://github.com/openspyrit/spyrit/blob/master/.github/workflows/example.py#L90
Because in this PR, you change this line: https://github.com/openspyrit/spyrit/pull/26/files#diff-1526dc6c0660985ae11e22bf5c2fa468ed221a033333ca26b5d6ba3af96aa750L445 where you remove device. Are you sure your code is able to work on both GPU and CPU without the device parameter?

**Comment by nducros** [comment]
@atlorentemur I am training `compNet` right now. 

I had to modify `net.py` [here](https://github.com/openspyrit/spyrit/blob/dac5f28ded27f874896a7247c48a1e21faeb3a47/spyrit/learning/nets.py#L59) as num_img has been added compared to the version on `master` see [here](https://github.com/openspyrit/spyrit/blob/36c90d10e9ca4d82671d24d68db8257a4b8e1c4d/spyrit/learning/nets.py#L59)

**Comment by nducros** [comment]
@tbaudier Thanks. Not sure but seems to run on GPU under Windows. Anyway we could keep the device. Please can you put it back?

**Comment by tbaudier** [comment]
> @tbaudier Thanks. Not sure but seems to run on GPU under Windows. Anyway we could keep the device. Please can you put it back?

If I remember well, the model was created with GPU and when we want to execute the code on CPU (eg: for MAC, during CI, ...) we need to force to load the model as a CPU type

**Comment by atlorentemur** [comment]
@tbaudier 
J'ai une erreur dans le fichier d'exemples. Il n'arrive pas à faire un simple import sous windows, et je n'ai pas d'idée sur la nature du problème.
==============================================================
Traceback (most recent call last):
  File "..\.github\workflows\example.py", line 27, in <module>
    from spyrit.reconstruction.recon_functions import *
ModuleNotFoundError: No module named 'spyrit.reconstruction.recon_functions'
===============================================================
J'ai vérifié l'othrographe, et je ne pense pas que le problème vienne de là. En effet, je fais référence au sous-module spyrit/reconstruction/recon_functions :  
https://github.com/openspyrit/spyrit/blob/master_antonio/spyrit/reconstruction/recon_functions.py
Pourrais-tu nous aider stp?

**Comment by nducros** [comment]
@tbaudier I fixed the conflicts but it still complains about conflicting files! On my local version, I no longer have `<<<< ===== >>>>`. I probably miss something. Also, I modified the setup.py (copy and paste from `master`) as the file resulting from the merge made reference of fht and was referenced 0.14.0

**Comment by nducros** [comment]
Thanks! I used the function `walsh2_matrix` in `misc.walsh_hadamard`

**Pull request closed without merging**
